### PR TITLE
Added functionality to get languages

### PR DESCRIPTION
**Pull request by taconaut**
As I've got the need to get the available languages, I've implemented this functionality, which is included in this pull request:

- Added method getLanguages to TVDBApi
- Implemented TvdbParser.getLanguages(String urlString)
- Added unit test testGetLanguages()

### CODE REVIEW

**Comment by taconaut** [comment]
Hi @Omertron 

Thanks for merging :+1: 
When do you plan on releasing 1.8? I'd like to stay with a maven reference to use thetvdb API and would like to use the get languages method at some point.

**Comment by Omertron** [comment]
I should probably  release an update as it has been a while.

I will try and do it this week if I get a chance during a lunch hour.

**Comment by taconaut** [comment]
That would be great :+1:

**Comment by Omertron** [comment]
1.8 should be making its way through the release process now.

**Comment by taconaut** [comment]
Cheers, it made it into the maven repository

**Pull request merged**
